/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/state-tunnel';


export namespace Components {

  interface AmplifyAuthenticator {
    'content': Function;
    'signIn': Function;
  }
  interface AmplifyAuthenticatorAttributes extends StencilHTMLAttributes {
    'content'?: Function;
    'onAuthStateChange'?: (event: CustomEvent) => void;
    'signIn'?: Function;
  }

  interface AmplifyButton {
    'role': string;
    'type': string;
  }
  interface AmplifyButtonAttributes extends StencilHTMLAttributes {
    'role'?: string;
    'type'?: string;
  }

  interface AmplifyExamples {}
  interface AmplifyExamplesAttributes extends StencilHTMLAttributes {}

  interface RockPaperScissor {
    'icon': Function;
  }
  interface RockPaperScissorAttributes extends StencilHTMLAttributes {
    'icon'?: Function;
    'onChange'?: (event: CustomEvent) => void;
  }

  interface AmplifySignInPasswordField {
    'component': Function;
    'description': string | null;
    'fieldId': string;
    'inputProps': {
      type?: string;
      onChange?: (Event) => void;
    };
    'label': string | null;
  }
  interface AmplifySignInPasswordFieldAttributes extends StencilHTMLAttributes {
    'component'?: Function;
    'description'?: string | null;
    'fieldId'?: string;
    'inputProps'?: {
      type?: string;
      onChange?: (Event) => void;
    };
    'label'?: string | null;
  }

  interface AmplifySignInUsernameField {
    'component': Function;
    'description': string | null;
    'fieldId': string;
    'inputProps': {
      type?: string;
      onChange?: (Event) => void;
    };
    'label': string | null;
  }
  interface AmplifySignInUsernameFieldAttributes extends StencilHTMLAttributes {
    'component'?: Function;
    'description'?: string | null;
    'fieldId'?: string;
    'inputProps'?: {
      type?: string;
      onChange?: (Event) => void;
    };
    'label'?: string | null;
  }

  interface AmplifySignIn {
    'handleSubmit': (Event) => void;
    'validationErrors': string;
  }
  interface AmplifySignInAttributes extends StencilHTMLAttributes {
    'handleSubmit'?: (Event) => void;
    'validationErrors'?: string;
  }

  interface AmplifyTextField {
    'description': string | null;
    'fieldId': string;
    'inputProps': {
      type?: string;
      onInput?: (Event) => void;
    };
    'label': string | null;
  }
  interface AmplifyTextFieldAttributes extends StencilHTMLAttributes {
    'description'?: string | null;
    'fieldId'?: string;
    'inputProps'?: {
      type?: string;
      onInput?: (Event) => void;
    };
    'label'?: string | null;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AmplifyAuthenticator': Components.AmplifyAuthenticator;
    'AmplifyButton': Components.AmplifyButton;
    'AmplifyExamples': Components.AmplifyExamples;
    'RockPaperScissor': Components.RockPaperScissor;
    'AmplifySignInPasswordField': Components.AmplifySignInPasswordField;
    'AmplifySignInUsernameField': Components.AmplifySignInUsernameField;
    'AmplifySignIn': Components.AmplifySignIn;
    'AmplifyTextField': Components.AmplifyTextField;
  }

  interface StencilIntrinsicElements {
    'amplify-authenticator': Components.AmplifyAuthenticatorAttributes;
    'amplify-button': Components.AmplifyButtonAttributes;
    'amplify-examples': Components.AmplifyExamplesAttributes;
    'rock-paper-scissor': Components.RockPaperScissorAttributes;
    'amplify-sign-in-password-field': Components.AmplifySignInPasswordFieldAttributes;
    'amplify-sign-in-username-field': Components.AmplifySignInUsernameFieldAttributes;
    'amplify-sign-in': Components.AmplifySignInAttributes;
    'amplify-text-field': Components.AmplifyTextFieldAttributes;
  }


  interface HTMLAmplifyAuthenticatorElement extends Components.AmplifyAuthenticator, HTMLStencilElement {}
  var HTMLAmplifyAuthenticatorElement: {
    prototype: HTMLAmplifyAuthenticatorElement;
    new (): HTMLAmplifyAuthenticatorElement;
  };

  interface HTMLAmplifyButtonElement extends Components.AmplifyButton, HTMLStencilElement {}
  var HTMLAmplifyButtonElement: {
    prototype: HTMLAmplifyButtonElement;
    new (): HTMLAmplifyButtonElement;
  };

  interface HTMLAmplifyExamplesElement extends Components.AmplifyExamples, HTMLStencilElement {}
  var HTMLAmplifyExamplesElement: {
    prototype: HTMLAmplifyExamplesElement;
    new (): HTMLAmplifyExamplesElement;
  };

  interface HTMLRockPaperScissorElement extends Components.RockPaperScissor, HTMLStencilElement {}
  var HTMLRockPaperScissorElement: {
    prototype: HTMLRockPaperScissorElement;
    new (): HTMLRockPaperScissorElement;
  };

  interface HTMLAmplifySignInPasswordFieldElement extends Components.AmplifySignInPasswordField, HTMLStencilElement {}
  var HTMLAmplifySignInPasswordFieldElement: {
    prototype: HTMLAmplifySignInPasswordFieldElement;
    new (): HTMLAmplifySignInPasswordFieldElement;
  };

  interface HTMLAmplifySignInUsernameFieldElement extends Components.AmplifySignInUsernameField, HTMLStencilElement {}
  var HTMLAmplifySignInUsernameFieldElement: {
    prototype: HTMLAmplifySignInUsernameFieldElement;
    new (): HTMLAmplifySignInUsernameFieldElement;
  };

  interface HTMLAmplifySignInElement extends Components.AmplifySignIn, HTMLStencilElement {}
  var HTMLAmplifySignInElement: {
    prototype: HTMLAmplifySignInElement;
    new (): HTMLAmplifySignInElement;
  };

  interface HTMLAmplifyTextFieldElement extends Components.AmplifyTextField, HTMLStencilElement {}
  var HTMLAmplifyTextFieldElement: {
    prototype: HTMLAmplifyTextFieldElement;
    new (): HTMLAmplifyTextFieldElement;
  };

  interface HTMLElementTagNameMap {
    'amplify-authenticator': HTMLAmplifyAuthenticatorElement
    'amplify-button': HTMLAmplifyButtonElement
    'amplify-examples': HTMLAmplifyExamplesElement
    'rock-paper-scissor': HTMLRockPaperScissorElement
    'amplify-sign-in-password-field': HTMLAmplifySignInPasswordFieldElement
    'amplify-sign-in-username-field': HTMLAmplifySignInUsernameFieldElement
    'amplify-sign-in': HTMLAmplifySignInElement
    'amplify-text-field': HTMLAmplifyTextFieldElement
  }

  interface ElementTagNameMap {
    'amplify-authenticator': HTMLAmplifyAuthenticatorElement;
    'amplify-button': HTMLAmplifyButtonElement;
    'amplify-examples': HTMLAmplifyExamplesElement;
    'rock-paper-scissor': HTMLRockPaperScissorElement;
    'amplify-sign-in-password-field': HTMLAmplifySignInPasswordFieldElement;
    'amplify-sign-in-username-field': HTMLAmplifySignInUsernameFieldElement;
    'amplify-sign-in': HTMLAmplifySignInElement;
    'amplify-text-field': HTMLAmplifyTextFieldElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
